---

- name: Processes groups and their members
  include_tasks: process_one_group.yml
  loop: "{{ identities.groups }}"
  loop_control:
    loop_var: group_data
  when:
    - identities.groups|length > 0
    - group_data.targets is undefined or
      'aws' in group_data.targets
    - group_data.state|default('present') == 'present'
