---

# Create a user
- name: Create user and gather user info
  include_tasks: process_one_user.yml
  loop: "{{ identities.users|flatten(levels=1) }}"
  loop_control:
    loop_var: user_data
  when:
    - identities.users|length > 0
    - user_data.targets is undefined or 'aws' in user_data.targets
    - user_data.state|default('present') == 'present'
