---

- name: Processes custom managed IAM policies
  iam_managed_policy:
    policy_name: "{{ policy_data.policy_name }}"
    policy_description: "{{ policy_data.policy_description|default(omit) }}"
    policy: "{{ policy_data.policy|from_yaml }}"
    make_default: "{{ policy_data.make_default|default(omit) }}"
    only_version: "{{ policy_data.only_version|default(omit) }}"
    profile: "{{ profile_data.profile_name }}"
    state: present
  loop: "{{ profile_data.policies }}"
  register: policy_output
  loop_control:
    loop_var: policy_data
  when:
    - profile_data.policies|length > 0
    - policy_data.targets is undefined or 'aws' in identities.targets
    - policy_data.state|default('present') == 'present'

