---

- name: Create user(s)
  iam_user:
    name: "{{ user_data.user_name }}"
    state: present
  register: _create_user

# Set initial password for new users
- block:
  - name: Create random password
    set_fact:
      initial_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"

  - name: Set initial password for user
    command: "aws iam create-login-profile --user-name {{ user_data.user_name }} --password {{ initial_password }} --password-reset-required"
  - debug:
      msg:
        - "Username: {{ user_data.user_name }}"
        - "Password: {{ initial_password }}"
        - "User must change password at next logon"
  when: _create_user.changed
  no_log: True
