---
- block: # when ansible_tower.schedules is defined
    - name: "Set default values"
      set_fact:
        processed_schedules: []

    - name: "Process the inventory schedules"
      include_tasks: process-schedule.yml
      with_items:
        - "{{ ansible_tower.schedules }}"
      loop_control:
        loop_var: schedule

  when:
    - ansible_tower.schedules is defined
