---

- name: "Copy custom Tower SSL certificate and Key"
  block:
  - copy:
      src: "{{ ansible_tower.install.ssl_certificate.cert }}"
      dest: /etc/tower/tower.cert
    notify:
    - reload-nginx

  - copy:
      src: "{{ ansible_tower.install.ssl_certificate.key }}"
      dest: /etc/tower/tower.key
    notify:
    - reload-nginx
  when:
  - ansible_tower.install.ssl_certificate is defined
  become: True
