---

- name: "Process password for AWS user(s)"
  block:
    - name: Set initial password for AWS user
      command: "aws iam create-login-profile --profile {{ identities.profiles.profile_name }} --user-name {{ identities.users.user_name }} --password {{ initial_password }} --password-reset-required"
    - debug:
        msg:
          - "Username: {{ identities.users.user_name }}"
          - "Password: {{ initial_password }}"
          - "User must change password at next login."
      with_items:
        - "{{ identities.users }}"
      loop_control:
        loop_var: user_data
      when:
        - identities.users is defined
        - identities.users|length > 0
        - user_data.targets is undefined or
          'aws' in user_data.targets
        - user_data.password is defined
        - user_data.password|trim != ''
  no_log: True
  when:
    - identities.targets is undefined or
      'aws' in identities.targets
