---

- name: "Process password for AWS user(s)"
  block:
    - name: Set initial password for AWS user
      command: "aws iam create-login-profile --profile {{ identities.users.aws_profile }} --user-name {{ identities.users.user_name }} --password {{ identities.users.password }} --password-reset-required"
      with_items:
        - "{{ identities.users }}"
      when:
        - identities.users is defined
        - identities.users|length > 0
        - identities.users.targets is undefined or
          'aws' in identities.users.targets
        - identities.users.password is defined
        - identities.users.password|trim != ''
  when:
    - identities.targets is undefined or
      'aws' in identities.targets
