name: Docker Image CI

on:
  push:
    branches: [ add_container_image ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file images/infra-ansible/python27/Containerfile --tag paulbarfuss/infra-ansible:$(date +%s)
