---

- name: "Force gather facts - an error is normal"
  setup:
  check_mode: no
  ignore_errors: True
  register: facts

- name: "Install dnf and selinux modules to allow for Ansible operation on legacy python2 systems"
  raw: dnf -y install python-dnf libselinux-python
  when:
    - facts is failed and
      ansible_python_version is defined and
      ansible_python_version is version('3', '<')

- name: "Install dnf and selinux modules to allow for Ansible operation on python3 systems"
  raw: dnf -y install python3-dnf python3-libselinux
  when:
    - facts is failed and
      ansible_python_version is defined and
      ansible_python_version is version('2', '>')
