---

- name: Check for Python shade module
  python_requirements_facts:
    dependencies:
      - shade

- import_tasks: "manage-networks.yml"

- import_tasks: "manage-subnets.yml"

- import_tasks: "manage-routers.yml"
